drop database if exists UNIVERSITY;
create database UNIVERSITY;
use UNIVERSITY;

create table DESIGNATION_T (
	DESIGNATION_ID int unsigned not null auto_increment,
    DESIGNATION_DESCRIPTION varchar(50) not null,
    primary key(DESIGNATION_ID)
);

create table EMPLOYEE_T (
	EMPLOYEE_ID int unsigned not null auto_increment,
	FIRST_NAME varchar(20) not null,
    LAST_NAME varchar(20) not null,
    DESIGNATION_ID int unsigned not null,
    primary key(EMPLOYEE_ID),
    foreign key(DESIGNATION_ID) references DESIGNATION_T(DESIGNATION_ID)
);

create table SALARY_T(
	SALARY_ID int unsigned not null auto_increment,
	QUANTITY decimal not null,
    EMPLOYEE_ID int unsigned not null,
    primary key(SALARY_ID),
    foreign key(EMPLOYEE_ID) references EMPLOYEE_T(EMPLOYEE_ID)
);

create table DEPARTMENT_T(
	DEPARTMENT_ID int unsigned not null auto_increment,
    DEPARTMENT_CODE varchar(10) not null,
    DEPARTMENT_DESCRIPTION varchar(50) not null,
    primary key(DEPARTMENT_ID)
);

create table DEPARTMENT_EMPLOYEE_T (
	DEPARTMENT_ID int unsigned not null,
	EMPLOYEE_ID int unsigned not null,
    primary key(DEPARTMENT_ID, EMPLOYEE_ID),
    foreign key(DEPARTMENT_ID) references DEPARTMENT_T(DEPARTMENT_ID),
    foreign key(EMPLOYEE_ID) references EMPLOYEE_T(EMPLOYEE_ID)
);

create view DEPARTMENT_STATISTIC as
	select
        DEPARTMENT_T.DEPARTMENT_ID,
        DEPARTMENT_T.DEPARTMENT_DESCRIPTION,
        (select CONCAT(EMPLOYEE_T.FIRST_NAME, ' ', EMPLOYEE_T.LAST_NAME) from EMPLOYEE_T 
        join DEPARTMENT_EMPLOYEE_T on EMPLOYEE_T.EMPLOYEE_ID = DEPARTMENT_EMPLOYEE_T.EMPLOYEE_ID
        where EMPLOYEE_T.DESIGNATION_ID = 1 and DEPARTMENT_EMPLOYEE_T.DEPARTMENT_ID = DEPARTMENT_T.DEPARTMENT_ID) as DEPARTMENT_DEAN,
        (select count(EMPLOYEE_T.EMPLOYEE_ID) from EMPLOYEE_T 
        join DEPARTMENT_EMPLOYEE_T on EMPLOYEE_T.EMPLOYEE_ID=DEPARTMENT_EMPLOYEE_T.EMPLOYEE_ID
        where EMPLOYEE_T.DESIGNATION_ID = 4 and DEPARTMENT_EMPLOYEE_T.DEPARTMENT_ID = DEPARTMENT_T.DEPARTMENT_ID) as ASSISTANT_AMOUNT,
        (select count(EMPLOYEE_T.EMPLOYEE_ID) from EMPLOYEE_T 
        join DEPARTMENT_EMPLOYEE_T on EMPLOYEE_T.EMPLOYEE_ID=DEPARTMENT_EMPLOYEE_T.EMPLOYEE_ID
        where EMPLOYEE_T.DESIGNATION_ID = 3 and DEPARTMENT_EMPLOYEE_T.DEPARTMENT_ID = DEPARTMENT_T.DEPARTMENT_ID) as ASSOCIATE_PROFESSORS_AMOUNT,
        (select count(EMPLOYEE_T.EMPLOYEE_ID) from EMPLOYEE_T 
        join DEPARTMENT_EMPLOYEE_T on EMPLOYEE_T.EMPLOYEE_ID=DEPARTMENT_EMPLOYEE_T.EMPLOYEE_ID
        where EMPLOYEE_T.DESIGNATION_ID = 2 and DEPARTMENT_EMPLOYEE_T.DEPARTMENT_ID = DEPARTMENT_T.DEPARTMENT_ID) as PROFESSORS_AMOUNT,
        (select ROUND(AVG(SALARY_T.QUANTITY), 2) from SALARY_T 
        join EMPLOYEE_T on SALARY_T.EMPLOYEE_ID = EMPLOYEE_T.EMPLOYEE_ID join DEPARTMENT_EMPLOYEE_T on EMPLOYEE_T.EMPLOYEE_ID = DEPARTMENT_EMPLOYEE_T.EMPLOYEE_ID
        where DEPARTMENT_T.DEPARTMENT_ID = DEPARTMENT_EMPLOYEE_T.DEPARTMENT_ID) as AVERAGE_SALARY
    from
		DEPARTMENT_T
;        

